name: Deploy to Firebase Hosting

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    env:
      GOOGLE_APPLICATION_CREDENTIALS: /tmp/sa.json

    steps:
      - uses: actions/checkout@v3

      - uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Instalar dependências
        run: npm install --legacy-peer-deps

      - name: Build
        run: npm run build

      - name: Salvar Service Account
        run: echo '${{ secrets.FIREBASE_SERVICE_ACCOUNT }}' > /tmp/sa.json

      - name: Instalar Firebase CLI
        run: npm install -g firebase-tools

      - name: Deploy
        run: firebase deploy --only hosting --project tiopatinhas-dd76e
